# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fe3b41b4f48ee7c49c97da87a7be60733f304b17ea3bfb84cd9b794991686f2d824c0823399f1ecdd4d6a1c986c5bc6a9a207532134a2a2634d9756c02c039f

test:
  secret_key_base: f5be4b18e9aa4fb293a5f3b39e5023d4436d6e9ea8955155b7c61036781630658170f469e22915b7744cbe954a142eed959ae797cbd363bb1e75d1275c067add

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
